"""Run a detached bond/LACP recorder on a Linux router so it survives LAN outages.

The recorder is started on the remote host under ``systemd-run`` (or ``nohup`` when
systemd is unavailable) and writes to the remote filesystem, so a lost SSH session or
a LAN outage during a LAG experiment does not end the recording. Fetch the results
afterwards with the ``fetch`` subcommand.

Recorded per run, all timestamps UTC:

- ``bond-states.txt``: full ``/proc/net/bonding/<bond>`` for each bond at every interval
  (aggregator IDs, churn states and counts, actor and partner LACPDU details).
- ``link-stats.txt``: ``ip -s -s link show`` for each interface at every interval.
- ``kernel-events.txt``: ``journalctl -k -f`` output (link up/down and bonding messages).
- ``<interface>.pcap``: tcpdump per interface, LACP/OAM only by default (EtherType 0x8809).
- ``host-info.txt``, ``started.txt``, ``finished.txt``.

Nothing managed by the router vendor is modified. The run directory defaults to
``/home/pi/lag-recorder``; a transient systemd unit is created and removed afterwards.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from tools.capture_support import private_directory, write_private

NAME_RE = re.compile(r"[a-zA-Z0-9][a-zA-Z0-9_.-]{0,14}")
LABEL_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,39}")
REMOTE_DIR_RE = re.compile(r"/[A-Za-z0-9_./-]+")
SSH_TARGET_RE = re.compile(r"[A-Za-z0-9_.@:\[\]-]+")
FILTER_RE = re.compile(r"[A-Za-z0-9 _:.\[\]()=&|!<>-]+")
DEFAULT_FILTER = "ether proto 0x8809"
HEREDOC = "QSW_RECORDER_EOF"

RECORDER_SCRIPT = r"""#!/bin/bash
# Generated by tools/firewalla_recorder.py. Runs detached on the router as root.
set -u
umask 077
RUN_DIR="$1"; DURATION="$2"; INTERVAL="$3"; SNAPLEN="$4"; PROMISC="$5"; FILTER="$6"
BONDS="$7"; IFACES="$8"
mkdir -p "$RUN_DIR" || exit 1
cd "$RUN_DIR" || exit 1
date -u +%FT%T.%3NZ > started.txt
{
  echo "hostname: $(hostname)"; uname -a; echo "utc: $(date -u)"
  echo "bonds: $BONDS"; echo "interfaces: $IFACES"; echo "filter: ${FILTER:-<none>}"
  echo "duration: $DURATION interval: $INTERVAL snaplen: $SNAPLEN promisc: ${PROMISC:-no}"
  for i in $IFACES; do ip -d link show "$i"; done
} > host-info.txt 2>&1
if command -v journalctl > /dev/null; then
  timeout "$DURATION" journalctl -k -f -o short-iso-precise --since now \
    > kernel-events.txt 2> kernel-events.err &
else
  timeout "$DURATION" dmesg -w -T > kernel-events.txt 2> kernel-events.err &
fi
for i in $IFACES; do
  # shellcheck disable=SC2086
  timeout "$DURATION" tcpdump $PROMISC -nn -e -U -i "$i" -s "$SNAPLEN" -w "$i.pcap" $FILTER \
    > "$i.tcpdump.txt" 2>&1 &
done
(
  end=$((SECONDS + DURATION))
  while [ "$SECONDS" -lt "$end" ]; do
    ts=$(date -u +%FT%T.%3NZ)
    {
      echo "=== $ts"
      for b in $BONDS; do echo "--- $b"; cat "/proc/net/bonding/$b" 2>&1; done
    } >> bond-states.txt
    {
      echo "=== $ts"
      for i in $IFACES; do ip -s -s link show "$i" 2>&1; done
    } >> link-stats.txt
    sleep "$INTERVAL"
  done
) &
wait
date -u +%FT%T.%3NZ > finished.txt
"""


def validate_names(values: list[str], what: str) -> list[str]:
    names = list(dict.fromkeys(values))
    for name in names:
        if not NAME_RE.fullmatch(name):
            raise ValueError(f"invalid {what} name: {name!r}")
    if not names:
        raise ValueError(f"at least one {what} is required")
    return names


def ssh_base(identity_file: Path, target: str) -> list[str]:
    if not SSH_TARGET_RE.fullmatch(target) or target.startswith("-"):
        raise ValueError("invalid SSH target")
    return [
        "ssh",
        "-i",
        str(identity_file),
        "-o",
        "BatchMode=yes",
        "-o",
        "IdentitiesOnly=yes",
        "-o",
        "StrictHostKeyChecking=yes",
        "-o",
        "ConnectTimeout=5",
        target,
    ]


def run_id(label: str, now: datetime | None = None) -> str:
    if not LABEL_RE.fullmatch(label):
        raise ValueError("label must be 1-40 characters of letters, digits, _ or -")
    stamp = (now or datetime.now(UTC)).strftime("%Y%m%dT%H%M%SZ")
    return f"{label}-{stamp}"


def recorder_arguments(
    run_dir: str,
    *,
    duration: int,
    interval: int,
    snaplen: int,
    promiscuous: bool,
    capture_filter: str,
    bonds: list[str],
    interfaces: list[str],
) -> list[str]:
    if not REMOTE_DIR_RE.fullmatch(run_dir) or "/../" in run_dir or run_dir.endswith("/.."):
        raise ValueError("remote run directory must be an absolute path without ..")
    if not 30 <= duration <= 14400:
        raise ValueError("duration must be 30-14400 seconds")
    if not 1 <= interval <= 30:
        raise ValueError("interval must be 1-30 seconds")
    if not 64 <= snaplen <= 65535:
        raise ValueError("snaplen must be 64-65535")
    if capture_filter and not FILTER_RE.fullmatch(capture_filter):
        raise ValueError("capture filter contains unsupported characters")
    return [
        run_dir,
        str(duration),
        str(interval),
        str(snaplen),
        "" if promiscuous else "-p",
        capture_filter,
        " ".join(validate_names(bonds, "bond")),
        " ".join(validate_names(interfaces, "interface")),
    ]


def bootstrap_script(run_dir: str, unit: str, arguments: list[str]) -> str:
    """Return the stdin script for ``sudo -n bash -s``: install the recorder, start it."""
    if HEREDOC in RECORDER_SCRIPT:
        raise ValueError("heredoc delimiter collides with the recorder script")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", unit):
        raise ValueError("invalid unit name")
    script_path = f"{run_dir}/recorder.sh"
    command = shlex.join(["/bin/bash", script_path, *arguments])
    return "\n".join(
        [
            "set -eu",
            "umask 077",
            f"mkdir -p {shlex.quote(run_dir)}",
            f"cat > {shlex.quote(script_path)} <<'{HEREDOC}'",
            RECORDER_SCRIPT.rstrip("\n"),
            HEREDOC,
            f"chmod 700 {shlex.quote(script_path)}",
            "if command -v systemd-run > /dev/null; then",
            f"  systemd-run --quiet --collect --unit={shlex.quote(unit)} "
            f"--property=TimeoutStopSec=20 {command}",
            "  echo started=systemd-run",
            "else",
            f"  nohup setsid {command} > /dev/null 2>&1 &",
            "  echo started=nohup",
            "fi",
            f"echo run_dir={shlex.quote(run_dir)}",
            "",
        ]
    )


def load_run(output: Path) -> dict:
    with (output / "run.json").open() as handle:
        return json.load(handle)


def ssh_run(ssh: list[str], command: str, *, stdin: str | None = None, timeout: int = 60):
    return subprocess.run(
        [*ssh, command],
        input=None if stdin is None else stdin.encode(),
        capture_output=True,
        timeout=timeout,
    )


def cmd_start(args: argparse.Namespace) -> int:
    ssh = ssh_base(args.identity_file, args.ssh_target)
    ident = run_id(args.label)
    run_dir = f"{args.remote_dir.rstrip('/')}/{ident}"
    unit = f"lag-recorder-{ident}"
    arguments = recorder_arguments(
        run_dir,
        duration=args.duration,
        interval=args.interval,
        snaplen=args.snaplen,
        promiscuous=args.promiscuous,
        capture_filter="" if args.capture_filter == "all" else args.capture_filter,
        bonds=args.bond,
        interfaces=args.interface,
    )
    script = bootstrap_script(run_dir, unit, arguments)
    private_directory(args.output)
    result = ssh_run(ssh, "sudo -n bash -s", stdin=script)
    record = {
        "started_utc": datetime.now(UTC).isoformat(),
        "ssh_target": args.ssh_target,
        "identity_file": str(args.identity_file),
        "remote_run_dir": run_dir,
        "unit": unit,
        "duration_seconds": args.duration,
        "interval_seconds": args.interval,
        "bonds": args.bond,
        "interfaces": args.interface,
        "capture_filter": args.capture_filter,
        "promiscuous_mode": args.promiscuous,
        "ssh_exit_status": result.returncode,
        "ssh_stdout": result.stdout.decode(errors="replace"),
        "ssh_stderr": result.stderr.decode(errors="replace"),
    }
    write_private(args.output / "run.json", json.dumps(record, indent=2).encode())
    print(json.dumps(record, indent=2))
    return 0 if result.returncode == 0 else 2


def cmd_status(args: argparse.Namespace) -> int:
    run = load_run(args.output)
    ssh = ssh_base(Path(run["identity_file"]), run["ssh_target"])
    command = " ; ".join(
        [
            f"systemctl is-active {shlex.quote(run['unit'])} 2>&1 || true",
            f"sudo -n ls -la {shlex.quote(run['remote_run_dir'])} 2>&1",
            f"sudo -n cat {shlex.quote(run['remote_run_dir'])}/finished.txt 2>/dev/null || true",
        ]
    )
    result = ssh_run(ssh, command)
    sys.stdout.write(result.stdout.decode(errors="replace"))
    sys.stderr.write(result.stderr.decode(errors="replace"))
    return 0 if result.returncode == 0 else 2


def cmd_stop(args: argparse.Namespace) -> int:
    run = load_run(args.output)
    ssh = ssh_base(Path(run["identity_file"]), run["ssh_target"])
    result = ssh_run(ssh, f"sudo -n systemctl stop {shlex.quote(run['unit'])} 2>&1 || true")
    sys.stdout.write(result.stdout.decode(errors="replace"))
    sys.stderr.write(result.stderr.decode(errors="replace"))
    return 0 if result.returncode == 0 else 2


def cmd_fetch(args: argparse.Namespace) -> int:
    run = load_run(args.output)
    ssh = ssh_base(Path(run["identity_file"]), run["ssh_target"])
    remote = run["remote_run_dir"]
    parent, name = remote.rsplit("/", 1)
    destination = args.output / "remote"
    private_directory(destination)
    result = ssh_run(
        ssh,
        f"sudo -n tar -C {shlex.quote(parent)} -cf - {shlex.quote(name)}",
        timeout=args.timeout,
    )
    if result.returncode != 0 or not result.stdout:
        sys.stderr.write(result.stderr.decode(errors="replace"))
        return 2
    write_private(args.output / "remote.tar", result.stdout)
    subprocess.run(
        [
            "tar",
            "-xf",
            str(args.output / "remote.tar"),
            "-C",
            str(destination),
            "--strip-components=1",
            "--no-same-owner",
        ],
        check=True,
    )
    for path in destination.rglob("*"):
        path.chmod(0o700 if path.is_dir() else 0o600)
    summary = {
        "fetched_utc": datetime.now(UTC).isoformat(),
        "files": {path.name: path.stat().st_size for path in sorted(destination.iterdir())},
    }
    for pcap in destination.glob("*.pcap"):
        header = pcap.read_bytes()[:4]
        summary.setdefault("pcap_header_ok", {})[pcap.name] = header in {
            b"\xd4\xc3\xb2\xa1",
            b"\xa1\xb2\xc3\xd4",
            b"\x4d\x3c\xb2\xa1",
            b"\xa1\xb2\x3c\x4d",
        }
    write_private(args.output / "fetch.json", json.dumps(summary, indent=2).encode())
    print(json.dumps(summary, indent=2))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    start = sub.add_parser("start", help="install and start a detached recorder run")
    start.add_argument("--ssh-target", required=True, help="user@host with existing SSH trust")
    start.add_argument("--identity-file", type=Path, required=True)
    start.add_argument("--bond", action="append", default=None, help="default: bond0 and bond1")
    start.add_argument(
        "--interface", action="append", default=None, help="default: eth0, eth1, eth2, eth3"
    )
    start.add_argument("--duration", type=int, default=900, help="seconds, 30-14400")
    start.add_argument("--interval", type=int, default=1, help="state sample interval, seconds")
    start.add_argument("--snaplen", type=int, default=256)
    start.add_argument(
        "--capture-filter",
        default=DEFAULT_FILTER,
        help="tcpdump filter per interface; 'all' captures every frame "
        f"(default: {DEFAULT_FILTER!r})",
    )
    start.add_argument("--promiscuous", action="store_true")
    start.add_argument("--remote-dir", default="/home/pi/lag-recorder")
    start.add_argument("--label", default="run")
    start.add_argument("--output", type=Path, required=True, help="new private local directory")
    start.set_defaults(func=cmd_start)

    for name, func, help_text in [
        ("status", cmd_status, "show unit state and remote files for a run"),
        ("stop", cmd_stop, "stop a run early"),
        ("fetch", cmd_fetch, "copy the remote run directory into <output>/remote"),
    ]:
        p = sub.add_parser(name, help=help_text)
        p.add_argument("--output", type=Path, required=True, help="directory holding run.json")
        if name == "fetch":
            p.add_argument("--timeout", type=int, default=300)
        p.set_defaults(func=func)

    args = parser.parse_args(argv)
    if args.command == "start":
        args.bond = args.bond or ["bond0", "bond1"]
        args.interface = args.interface or ["eth0", "eth1", "eth2", "eth3"]
    try:
        return args.func(args)
    except (ValueError, OSError, subprocess.TimeoutExpired, subprocess.CalledProcessError) as exc:
        parser.error(f"{type(exc).__name__}: {exc}")


if __name__ == "__main__":
    raise SystemExit(main())
